server:
  port: 9000
#  session:
#    timeout: 30

#
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/jeesite?useUnicode=true&characterEncoding=utf-8
   username: root
   password: 123123
   initial-size: 1
   min-idle: 1
   max-active: 20
   test-on-borrow: true


mybatis:
       type-aliases-package: cn.sierac.entity
       mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - cn.sierac.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql








